[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petal-clustering = "0.5.1"
wasm-bindgen = "0.2.84"

[lib]
crate-type = ["cdylib", "rlib"]

